// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RecruitmentBackend.Data;

#nullable disable

namespace OnBoarding.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RecruitmentBackend.Models.CandidateHobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AbilityLevel")
                        .HasColumnType("text");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HobbyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocalDescription")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CandidateHobbies");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.CandidateLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReadLevel")
                        .HasColumnType("text");

                    b.Property<string>("SpokenLevel")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WrittenLevel")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CandidateLanguages");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.CandidateResume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("FileContent")
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CandidateResumes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.CessationReason", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("rsgnrsncode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rsgnrsndesc");

                    b.HasKey("Code", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("cessation_reasons");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColourCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("colour_code");

                    b.Property<string>("CompanyDetails")
                        .HasColumnType("text")
                        .HasColumnName("company_details");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LogoPath")
                        .HasColumnType("text")
                        .HasColumnName("logo_path");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.ContactInformation", b =>
                {
                    b.Property<string>("CandidateId")
                        .HasColumnType("text")
                        .HasColumnName("candidate_id");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text")
                        .HasColumnName("company_id");

                    b.Property<string>("CorrespondenceAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correspondence_address");

                    b.Property<string>("CorrespondenceArea")
                        .HasColumnType("text")
                        .HasColumnName("correspondence_area");

                    b.Property<string>("CorrespondenceCity")
                        .HasColumnType("text")
                        .HasColumnName("correspondence_city");

                    b.Property<string>("CorrespondencePhone")
                        .HasColumnType("text")
                        .HasColumnName("correspondence_phone");

                    b.Property<string>("CorrespondenceState")
                        .HasColumnType("text")
                        .HasColumnName("correspondence_state");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("EmergencyAddress")
                        .HasColumnType("text")
                        .HasColumnName("emergency_address");

                    b.Property<string>("EmergencyNumber")
                        .HasColumnType("text")
                        .HasColumnName("emergency_number");

                    b.Property<string>("EmergencyPhone")
                        .HasColumnType("text")
                        .HasColumnName("emergency_phone");

                    b.Property<string>("EmployeeCandidateId")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeCompanyId")
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EmployeePositionCode")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OfficeNumber")
                        .HasColumnType("text")
                        .HasColumnName("office_number");

                    b.Property<string>("OtherNumber")
                        .HasColumnType("text")
                        .HasColumnName("other_number");

                    b.Property<string>("PermanentAddress")
                        .HasColumnType("text")
                        .HasColumnName("permanent_address");

                    b.Property<string>("PermanentPhone")
                        .HasColumnType("text")
                        .HasColumnName("permanent_phone");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CandidateId", "CompanyId");

                    b.HasIndex("EmployeeCandidateId", "EmployeeCompanyId", "EmployeePositionCode");

                    b.ToTable("ContactInformation");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.CountryOrigin", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("ctyorgcode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ctyorgname");

                    b.HasKey("Code", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("country_origin_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Employee", b =>
                {
                    b.Property<string>("CandidateId")
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PositionCode")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("CountryOfOriginCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Disability")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("MaritalStatusCode")
                        .HasColumnType("text");

                    b.Property<string>("NationalityCode")
                        .HasColumnType("text");

                    b.Property<string>("NativeStatus")
                        .HasColumnType("text");

                    b.Property<string>("NewIcNumber")
                        .HasColumnType("text");

                    b.Property<string>("OldIcNumber")
                        .HasColumnType("text");

                    b.Property<string>("Passport")
                        .HasColumnType("text");

                    b.Property<string>("RaceCode")
                        .HasColumnType("text");

                    b.Property<string>("RecommendationDetails")
                        .HasColumnType("text");

                    b.Property<string>("RecommendationType")
                        .HasColumnType("text");

                    b.Property<string>("Referee1")
                        .HasColumnType("text");

                    b.Property<string>("Referee2")
                        .HasColumnType("text");

                    b.Property<string>("ReligionCode")
                        .HasColumnType("text");

                    b.Property<string>("SalutationCode")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CandidateId", "CompanyId", "PositionCode");

                    b.HasIndex("CountryOfOriginCode", "CompanyId");

                    b.HasIndex("MaritalStatusCode", "CompanyId");

                    b.HasIndex("NationalityCode", "CompanyId");

                    b.HasIndex("PositionCode", "CompanyId");

                    b.HasIndex("RaceCode", "CompanyId");

                    b.HasIndex("ReligionCode", "CompanyId");

                    b.HasIndex("SalutationCode", "CompanyId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.EmploymentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CessationReasonCode")
                        .HasColumnType("text");

                    b.Property<string>("CessationReasonDescription")
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmphJobName")
                        .HasColumnType("text");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IndustryCode")
                        .HasColumnType("text");

                    b.Property<string>("JobCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobFunction")
                        .HasColumnType("text");

                    b.Property<string>("JobName")
                        .HasColumnType("text");

                    b.Property<decimal?>("LastSalary")
                        .HasColumnType("numeric");

                    b.Property<bool>("Latest")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("StartSalary")
                        .HasColumnType("numeric");

                    b.Property<string>("TelNo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("EmploymentHistories");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.FieldArea", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("fldareaid");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fldareaname");

                    b.HasKey("Code", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("field_area_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.FieldExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FieldAreaCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FieldExperiences");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Hobby", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("hbycode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hbyname");

                    b.HasKey("Code", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("hobby_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Industry", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("indstrycode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("indstryname");

                    b.HasKey("Code", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("industry_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Job", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("jobcode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jobpost");

                    b.HasKey("Code", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("job_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("langcode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("langname");

                    b.HasKey("Code", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("language_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.MaritalStatus", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("marstacode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("marstaname");

                    b.HasKey("Code", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("marital_status_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Nationality", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("nationcode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nationame");

                    b.HasKey("Code", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("nationality_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Position", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("jobcode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jobpost");

                    b.HasKey("Code", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("position_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Qualification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CGPA")
                        .HasColumnType("text");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsHighest")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinSchoolDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OtherGradeInfo")
                        .HasColumnType("text");

                    b.Property<string>("QualificationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QualificationGradeCode")
                        .HasColumnType("text");

                    b.Property<string>("QualificationGradeName")
                        .HasColumnType("text");

                    b.Property<string>("QualificationGradeRank")
                        .HasColumnType("text");

                    b.Property<string>("QualificationName")
                        .HasColumnType("text");

                    b.Property<string>("QualificationSubCode")
                        .HasColumnType("text");

                    b.Property<string>("QualificationSubName")
                        .HasColumnType("text");

                    b.Property<string>("SchoolAddress")
                        .HasColumnType("text");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchoolTelNo")
                        .HasColumnType("text");

                    b.Property<DateTime>("SinceWhenDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.QualificationCode", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("qlfcatid");

                    b.Property<string>("SubCode")
                        .HasColumnType("text")
                        .HasColumnName("qlfsubid");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qlfcatname");

                    b.Property<string>("SubName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qlfsubname");

                    b.HasKey("Code", "SubCode", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("qualification_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.QualificationGrade", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("qlfgradecode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qlfgradename");

                    b.HasKey("Code", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("qualification_grades");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Race", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("racecode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("racename");

                    b.HasKey("Code", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("race_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Religion", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("religncode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relignname");

                    b.HasKey("Code", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("religion_codes");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Salutation", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text")
                        .HasColumnName("salucode");

                    b.Property<string>("CompanyId")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("saludesc");

                    b.HasKey("Code", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("salutation_code");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Skill", b =>
                {
                    b.Property<string>("CandidateId")
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OfficeSkills")
                        .HasColumnType("text");

                    b.Property<string>("OtherRelevantSkills")
                        .HasColumnType("text");

                    b.Property<string>("OtherSkillInformation")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CandidateId", "CompanyId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CandidateId")
                        .HasColumnType("text");

                    b.Property<string>("CompanyId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IcNumber")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email", "CompanyId")
                        .IsUnique();

                    b.HasIndex("IcNumber", "CompanyId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.CessationReason", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.ContactInformation", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeCandidateId", "EmployeeCompanyId", "EmployeePositionCode");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.CountryOrigin", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Employee", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.CountryOrigin", "CountryOfOrigin")
                        .WithMany()
                        .HasForeignKey("CountryOfOriginCode", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecruitmentBackend.Models.MaritalStatus", "MaritalStatus")
                        .WithMany()
                        .HasForeignKey("MaritalStatusCode", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecruitmentBackend.Models.Nationality", "Nationality")
                        .WithMany()
                        .HasForeignKey("NationalityCode", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecruitmentBackend.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionCode", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecruitmentBackend.Models.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceCode", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecruitmentBackend.Models.Religion", "Religion")
                        .WithMany()
                        .HasForeignKey("ReligionCode", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RecruitmentBackend.Models.Salutation", "Salutation")
                        .WithMany()
                        .HasForeignKey("SalutationCode", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CountryOfOrigin");

                    b.Navigation("MaritalStatus");

                    b.Navigation("Nationality");

                    b.Navigation("Position");

                    b.Navigation("Race");

                    b.Navigation("Religion");

                    b.Navigation("Salutation");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.FieldArea", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Hobby", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Industry", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Job", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Language", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.MaritalStatus", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Nationality", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Position", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.QualificationCode", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.QualificationGrade", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Race", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Religion", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("RecruitmentBackend.Models.Salutation", b =>
                {
                    b.HasOne("RecruitmentBackend.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .HasPrincipalKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
